[workspace]
resolver = "2"
members = [
    "venator",
    "venator-app/src-tauri",
    "venator-engine",
]

[profile.release]
codegen-units = 1
lto = true
strip = true

[patch.crates-io]
venator-engine = { path = "./venator-engine" }